title: JB McGee dev
author: JBM
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Are you looking for me? Here I am. Come and see what I've been up to here on Github. I've been hard at work for the last 45 minutes! And hard work pays off.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
